# Generated by Django 2.1.1 on 2020-01-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshoot', '0002_auto_20200130_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitshoot_table',
            name='production_line',
            field=models.IntegerField(),
        ),
    ]
