# Generated by Django 2.1.1 on 2020-01-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitshoot', '0003_auto_20200130_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitshoot_table',
            name='spout',
            field=models.IntegerField(default=-1),
        ),
    ]
