# Generated by Django 2.0.5 on 2018-09-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Values_in_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_time', models.IntegerField()),
                ('line', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('a_ok', models.IntegerField()),
                ('b_ok', models.IntegerField()),
                ('combined_side_a_ng', models.IntegerField()),
                ('combined_side_b_ng', models.IntegerField()),
                ('a_top_ng', models.IntegerField()),
                ('b_top_ng', models.IntegerField()),
                ('a_bottom_ng', models.IntegerField()),
                ('b_bottom_ng', models.IntegerField()),
                ('a_side_ng', models.IntegerField()),
                ('b_side_ng', models.IntegerField()),
                ('combined_side_a_re', models.IntegerField()),
                ('a_top_re', models.IntegerField()),
                ('b_top_re', models.IntegerField()),
                ('a_bottom_re', models.IntegerField()),
                ('b_bottom_re', models.IntegerField()),
                ('a_side_re', models.IntegerField()),
                ('b_side_re', models.IntegerField()),
            ],
        ),
    ]
