# Generated by Django 2.1.1 on 2018-09-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0002_values_in_db_combined_side_b_re'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolceGusto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_date', models.DateTimeField()),
                ('line', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('a_ok', models.IntegerField()),
                ('b_ok', models.IntegerField()),
                ('combined_side_a_ng', models.IntegerField()),
                ('combined_side_b_ng', models.IntegerField()),
                ('a_top_ng', models.IntegerField()),
                ('b_top_ng', models.IntegerField()),
                ('a_bottom_ng', models.IntegerField()),
                ('b_bottom_ng', models.IntegerField()),
                ('a_side_ng', models.IntegerField()),
                ('b_side_ng', models.IntegerField()),
                ('combined_side_a_re', models.IntegerField()),
                ('combined_side_b_re', models.IntegerField()),
                ('a_top_re', models.IntegerField()),
                ('b_top_re', models.IntegerField()),
                ('a_bottom_re', models.IntegerField()),
                ('b_bottom_re', models.IntegerField()),
                ('a_side_re', models.IntegerField()),
                ('b_side_re', models.IntegerField()),
            ],
        ),
    ]
