# Generated by Django 2.1.1 on 2018-09-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0003_dolcegusto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Values_in_db',
        ),
    ]
