# Generated by Django 2.1.1 on 2018-09-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0004_delete_values_in_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolcegusto',
            name='csv_time',
            field=models.TimeField(default="00:00"),
        ),
        migrations.AlterField(
            model_name='dolcegusto',
            name='csv_date',
            field=models.DateField(),
        ),
    ]
