# Generated by Django 2.1.1 on 2018-09-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0005_auto_20180913_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolcegusto',
            name='a_bottom_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='a_bottom_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='a_ok',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='a_side_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='a_side_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='a_top_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='a_top_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='b_bottom_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='b_bottom_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='b_ok',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='b_side_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='b_side_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='b_top_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='b_top_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='combined_side_a_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='combined_side_a_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='combined_side_b_ng',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='combined_side_b_re',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='csv_date',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='csv_time',
        ),
        migrations.RemoveField(
            model_name='dolcegusto',
            name='line',
        ),
    ]
