# Generated by Django 2.1.1 on 2018-09-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0008_auto_20180913_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolcegusto',
            name='csv_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dolcegusto',
            name='csv_time',
            field=models.TimeField(),
        ),
    ]
