# Generated by Django 2.1.1 on 2018-09-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0010_auto_20180913_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolcegusto',
            name='csv_datetime',
            field=models.DateTimeField(default='1980-09-25 00:00'),
        ),
    ]
