# Generated by Django 2.1.1 on 2018-09-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0011_auto_20180913_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='DolceGusto_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_datetime', models.DateTimeField("1980-09-25 00:00")),
                ('line', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('a_ok', models.IntegerField()),
                ('b_ok', models.IntegerField()),
                ('combined_side_a_ng', models.IntegerField()),
                ('combined_side_b_ng', models.IntegerField()),
                ('a_top_ng', models.IntegerField()),
                ('b_top_ng', models.IntegerField()),
                ('a_bottom_ng', models.IntegerField()),
                ('b_bottom_ng', models.IntegerField()),
                ('a_side_ng', models.IntegerField()),
                ('b_side_ng', models.IntegerField()),
                ('combined_side_a_re', models.IntegerField()),
                ('combined_side_b_re', models.IntegerField()),
                ('a_top_re', models.IntegerField()),
                ('b_top_re', models.IntegerField()),
                ('a_bottom_re', models.IntegerField()),
                ('b_bottom_re', models.IntegerField()),
                ('a_side_re', models.IntegerField()),
                ('b_side_re', models.IntegerField()),
            ],
        ),
    ]
