# Generated by Django 2.1.1 on 2018-09-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0013_remove_dolcegusto_csv_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolcegusto',
            name='raw_time',
            field=models.IntegerField(default=0),
        ),
    ]
