# Generated by Django 2.1.1 on 2018-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0014_dolcegusto_raw_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_date', models.DateField("1980-09-25")),
            ],
        ),
        migrations.RemoveField(
            model_name='dolcegusto_table',
            name='csv_datetime',
        ),
    ]
