# Generated by Django 2.1.1 on 2018-09-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0016_auto_20180917_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_date',
            name='csv_date',
            field=models.DateField(default='1980-09-25'),
        ),
        migrations.AlterField(
            model_name='dolcegusto_table',
            name='date_of_csv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dolcegusto.CSV_Date'),
        ),
    ]
