# Generated by Django 2.1.1 on 2018-09-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0017_auto_20180917_1522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DolceGusto',
        ),
    ]
