# Generated by Django 2.1.1 on 2018-09-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0019_auto_20180919_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dolcegusto_table',
            old_name='csv_date',
            new_name='date_of_csv',
        ),
    ]
