# Generated by Django 2.1.1 on 2018-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0020_auto_20180919_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolcegusto_table',
            name='date_of_csv',
        ),
        migrations.RemoveField(
            model_name='dolcegusto_table',
            name='time_of_csv',
        ),
        migrations.AddField(
            model_name='dolcegusto_table',
            name='csv_datetime',
            field=models.DateTimeField(default='1980-09-25 00:00:00'),
        ),
    ]
