# Generated by Django 2.1.1 on 2018-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0021_auto_20180920_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='dolcegusto_table',
            name='saving_datetime',
            field=models.DateTimeField(default='2018-09-25 00:00:00'),
        ),
    ]
