# Generated by Django 2.1.1 on 2018-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0022_dolcegusto_table_saving_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolcegusto_table',
            name='csv_datetime',
            field=models.DateTimeField(default='1980-09-25 00:00:00', max_length=9),
        ),
    ]
