# Generated by Django 2.1.1 on 2018-09-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0023_auto_20180921_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dolcegusto_table',
            name='saving_datetime',
        ),
    ]
