# Generated by Django 2.1.2 on 2018-10-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0025_past_week'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='past_week',
            table='past_week',
        ),
    ]
