# Generated by Django 2.1.1 on 2018-11-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolcegusto', '0027_auto_20181113_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolcegusto_table',
            name='product',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dolcegusto_table',
            name='production_site',
            field=models.CharField(max_length=30),
        ),
    ]
