# Generated by Django 2.1.1 on 2020-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_flip_i2s', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secureflip_i2s_table',
            name='program',
            field=models.CharField(max_length=60),
        ),
    ]
